#set(CMAKE_PREFIX_PATH "/home/slam/UntouchWorkspace/Thirdparty/free/x86_64-linux/CMake-hdf5-1.10.1/hdf5-1.10.1/build/install/share/cmake;${CMAKE_PREFIX_PATH}")
#include(/home/slam/UntouchWorkspace/Thirdparty/free/x86_64-linux/CMake-hdf5-1.10.1/hdf5-1.10.1/build/install/share/cmake/hdf5-config.cmake)
find_package(HDF5)
if(HDF5_FOUND)
  list(APPEND DEST_LINK_TARGETS hdf5)
  list(APPEND DEST_LINK_TARGETS hdf5_hl)
  list(APPEND DEST_LINK_TARGETS hdf5_cpp)
  list(APPEND DEST_LINK_TARGETS hdf5_hl_cpp)
#  list(APPEND DEST_LINK_TARGETS hdf5_tools)
  list(APPEND DEST_INCLUDE_DIRS ${HDF5_INCLUDE_DIR})
  message(STATUS "Compile With HDF5 : ${DEST_LINK_TARGETS}")
else()
  message(STATUS "Can not find HDF5...")
endif()
