#set(HDF5_PATH "/home/lowell/softwares/hdf5-1.10.1/build/install/share/cmake")

#find_package(HDF5 REQUIRED PATHS ${HDF5_PATH} NO_DEFAULT_PATH)
find_package(HDF5 REQUIRED)
if(HDF5_FOUND)
  list(APPEND DEST_LINK_TARGETS hdf5)
  list(APPEND DEST_LINK_TARGETS hdf5_hl)
  list(APPEND DEST_LINK_TARGETS hdf5_cpp)
  list(APPEND DEST_LINK_TARGETS hdf5_hl_cpp)
#  list(APPEND DEST_LINK_TARGETS hdf5_tools)
  list(APPEND DEST_INCLUDE_DIRS ${HDF5_INCLUDE_DIR})
  message(STATUS "Compile With HDF5 : ${HDF5_CXX_LIBRARIES}")
else()
  message(STATUS "Can not find HDF5...")
endif()
